version: '3.9'

services:
  app:
    build: .
    container_name: app-registration-api
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/jrtp_nt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Taufikh#84
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8081
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-jrtp
    environment:
      MYSQL_ROOT_PASSWORD: Taufikh#84
      MYSQL_DATABASE: jrtp_nt
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pTaufikh#84"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge